wip

diff --git a/.github/workflows/lint-code.yml b/.github/workflows/lint-code.yml
--- a/.github/workflows/lint-code.yml
+++ b/.github/workflows/lint-code.yml
@@ -31,8 +31,7 @@ jobs:
           python -m pip install --upgrade pip
           pip install isort
       - name: isort --> Check for best-practice sorting of imports
-        run: |
-        isort --check . || echo "::error ::Please run 'isort .' on this repo." && exit 1
+        run: isort --check . || echo "::error ::Please run isort . on this repo." && exit 1
 
   ruff-format:
     runs-on: ubuntu-latest
